-- File generated by the Hercules naviluagenerator plugin
-- http://herc.ws / http://github.com/HerculesWS/StaffPlugins
-- Last Change: 2022-06-11

Navi_NpcDistance = {
"alb2trea", 1, {
 { 11984, -- GID (±´¶ûÄá#alb2trea alb2trea,58,68)
  { "treasure01", 13869, 46 }, -- Srcmap, gid, dist (treasure01,69,22)
  { "", 0, 0 }
 },
},
"alberta", 1, {
 { 11985, -- GID (±´¶ûÄá#alberta alberta,196,213)
  { "pay_fild03", 13683, 237 }, -- Srcmap, gid, dist (pay_fild03,392,63)
  { "alberta_in", 14097, 119 }, -- Srcmap, gid, dist (alberta_in,189,89)
  { "alberta_in", 14098, 143 }, -- Srcmap, gid, dist (alberta_in,114,130)
  { "alberta_in", 14099, 215 }, -- Srcmap, gid, dist (alberta_in,14,141)
  { "alberta_in", 14100, 200 }, -- Srcmap, gid, dist (alberta_in,180,34)
  { "alberta_in", 14101, 204 }, -- Srcmap, gid, dist (alberta_in,73,141)
  { "alberta_in", 14102, 220 }, -- Srcmap, gid, dist (alberta_in,78,44)
  { "alberta_in", 14103, 164 }, -- Srcmap, gid, dist (alberta_in,125,161)
  { "", 0, 0 }
 },
},
"izlude", 1, {
 { 11986, -- GID (ÀÏÇÇÄá#izlude izlude,196,213)
  { "prt_fild08", 13773, 227 }, -- Srcmap, gid, dist (prt_fild08,371,212)
  { "izlude_in", 13935, 83 }, -- Srcmap, gid, dist (izlude_in,116,46)
  { "izlude_in", 13937, 103 }, -- Srcmap, gid, dist (izlude_in,65,84)
  { "", 0, 0 }
 },
},
"izlu2dun", 1, {
 { 11987, -- GID (Â¬µÇ#izlu2dun izlu2dun,105,29)
  { "iz_dun00", 13533, 190 }, -- Srcmap, gid, dist (iz_dun00,168,173)
  { "", 0, 0 }
 },
},
}
