-- File generated by the Hercules naviluagenerator plugin
-- http://herc.ws / http://github.com/HerculesWS/StaffPlugins
-- Last Change: 2022-06-11

Navi_Npc = {
{ "alb2trea", 11984, 101, 100, "±´¶ûÄá", "", 58, 68, },
{ "alberta", 11985, 101, 100, "±´¶ûÄá", "", 196, 213, },
{ "izlude", 11986, 101, 120, "ÀÏÇÇÄá", "", 196, 213, },
{ "izlu2dun", 11987, 101, 98, "Â¬µÇ", "", 105, 29, },
}
